### PR TITLE
add authentication to main controllers

### PR DESCRIPTION
**Pull request by linedotstar**
#3 

This also includes updating the nav to Bootstrap 4 styles.

### CODE REVIEW

**Comment by apurvis** [comment]
i'm not good at haml so it's hard for me to tell exactly what's going on.  the idea is to have 3 user roles

1. viewer (cannot edit/add)
2. vip (can edit and add records, but cannot see user list)
3. can see list of users and invite new users, as per https://github.com/apurvis/rader/issues/4

although, re: that 3rd part i was also considering no email integration and just that people have to have their accounts manually created.  this is partially because we are thinking of ultimately hosting the site on TOR / deep web style and not on the "real" web, in which case i'm not sure invite links help.

**Comment by apurvis** [comment]
also before you merge this - which i'm thinking will make it harder for people to sign in - can you create an account in the prod DB so that I can send login / pass to the lawyers so that they can login and see stuff?  

doesn't have to be super secure i just need them to be able to play with the app.

**Comment by linedotstar** [comment]
If there is no auth, the visitor can only see sign up pages
If there is an auth,
  and the user is an admin, they can see all pages and links including the /admin ones
  and the user is not an admin, they can see all pages and links except the /admin ones

**Comment by apurvis** [comment]
cool to merge just please go in the prod DB and create a user / pass somehow so i can give it to the lawyers.  (obviously we'll create a different admin user/pass once people are using this)

**Review by apurvis — APPROVED** [review]

**Comment by apurvis** [comment]
(just email me the admin user/pass you create once it's out there)

**Comment by apurvis** [comment]
at the moment, there's no link anywhere to the list of users that i would sort of expect to see as the admin user? maybe i just missed it?  but the admin should be able to delete users and eventually add them ... should i just open another issue about that or is there an admin page i'm not seeing or something?

p.s. i forced myself to learn haml to do this so i hope that makes you happy, because to me it just seems like  pain in the ass vs. good old ERB lol

**Comment by linedotstar** [comment]
The user I created isn't an admin so they won't see those links. The link is here though: https://github.com/apurvis/rader/pull/16/files#diff-3b4b7d61377864ca600a7568f652deb1R10

**Comment by linedotstar** [comment]
I just changed the user role to admin

**Comment by apurvis** [comment]
👍

**Pull request merged**
